// --------- INPUT --------- //
export const INPUT_EMAIL = "INPUT_EMAIL";
export const INPUT_PASSWORD = "INPUT_PASSWORD";
export const INPUT_CONFIRM_PASSWORD = "INPUT_CONFIRM_PASSWORD";

// --------- AUTHENTICATION --------- // 
export const AUTH_WAITING_FOR_SIGNIN = "AUTH_WAITING_FOR_SIGNIN";
export const AUTH_SUCCESSFULLY = "AUTH_SUCCESSFULLY";
export const AUTH_UNSUCCESSFULLY = "AUTH_UNSUCCESSFULLY";
export const AUTH_RESET_INFORMATION = "AUTH_RESET_INFORMATION";
export const AUTH_CREATING_ACCOUNT = "AUTH_CREATING_ACCOUNT";
export const AUTH_CREATE_SUCCESSFULLY = "AUTH_CREATE_SUCCESSFULLY";
export const AUTH_CREATE_UNSUCCESSFULLY = "AUTH_CREATE_UNSUCCESSFULLY";
export const AUTH_SIGN_OUT_SUCCESSFULLY = "AUTH_SIGN_OUT_SUCCESSFULLY";
export const AUTH_GET_INCART_ITEMS = "AUTH_GET_INCART_ITEMS"

// --------- SHOPPING --------- //
export const PUR_ADDING_TO_CART = "PUR_ADDING_TO_CART";
export const PUR_ADDING_TO_CART_SUCCESSFULLY = "PUR_ADDING_TO_CART_SUCCESSFULLY";
export const PUR_ADDING_TO_CART_UNSUCCESSFULLY = "PUR_ADDING_TO_CART_UNSUCCESSFULLY";
export const PUR_CLOSE_ATC_MODAL = "PUR_CLOSE_ATC_MODAL";
